# Form implementation generated from reading ui file 'badger.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class badgerteriminal(object):
    def setupUi(self, badgerterminal):
        badgerterminal.setObjectName("badegrterminal")
        # badgerterminal.resize(1178, 624)
      
        self.treeWidget = QtWidgets.QTreeWidget(parent=badgerterminal)
        self.treeWidget.setFixedHeight(100)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=badgerterminal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        # self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 1121, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(badgerterminal)
        QtCore.QMetaObject.connectSlotsByName(badgerterminal)

    def retranslateUi(self, badgerterminal):
        _translate = QtCore.QCoreApplication.translate
        badgerterminal.setWindowTitle(_translate("badgerterminal", "badgerterminal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    badgerterminal = QtWidgets.QDialog()
    ui = badgerteriminal()
    ui.setupUi(badgerterminal)
    badgerterminal.show()
    sys.exit(app.exec())
